### ISSUE TITLE
freetool包没有编译成js，导致项目运行报错

### ISSUE THREAD

**Issue by cch6** [FreemenL/emptyd-admin-webpack#1]
rt。
直接拉项目，安装好依赖后，无法启动

freetool这个包导致的。npm包发布的时候没有编译成js文件
并且此项目ts loader没有处理node_modules文件夹。

两个项目的作者都是你，你看看改一下这个项目，或者哪个包的项目吧

**Comment by FreemenL** [comment]
> RT，
> 直接拉项目，安装好依赖后，无法启动
> 
> freetool这个包导致的.npm包发布的时候没有编译成js文件
> 并且此项目ts loader没有处理node_modules文件夹。
> 
> 两个项目的作者都是你，你看看改一下这个项目，或者哪个包的项目吧

**Comment by FreemenL** [comment]
> RT，
> 直接拉项目，安装好依赖后，无法启动
> 
> freetool这个包导致的.npm包发布的时候没有编译成js文件
> 并且此项目ts loader没有处理node_modules文件夹。
> 
> 两个项目的作者都是你，你看看改一下这个项目，或者哪个包的项目吧

在 config/index.js  
修改 配置项    appTsLoader: ['node_modules/_free-validator@1.0.7@free-validator', 'node_modules/_freetool@0.0.3@freetool']
改成    appTsLoader: ['node_modules/free-validator', 'node_modules/freetool'] 试下 应该是这个地方的问题
